language: javascript
before_script:
  - npm install jshint --prefix .
  - npm install jscs --prefix .
script:
  - ./node_modules/jshint/bin/jshint sherdjs/src
  - ./node_modules/jscs/bin/jscs sherdjs/src
